version: '3.1'

services:
  postgres:
    image: postgres:13.6-alpine
    restart: always
    environment:
      POSTGRES_USER: db-query-analyzer
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pg_data:
